### PR TITLE
#15: Reset Password Prompt Page

### LINKED ISSUE #15: Reset Password Prompt Page
### Ticket
As a youth, I want to be able to reset my password if I have forgotten it.

### Acceptance Criteria 
Given I want to use the app, when I want to tap on the "Forgot Password?", then I am redirected to a new page to reset my password.

### Subtasks
- Potential subtasks that may be an extension of this is to have an email reset system
     - figure out how to send the email (using what email? what API?)

### Details: Technical Specifications
Things to include on the reset page:
- Enter the email address to reset the password.
- Need to figure how to generate a unique password reset link that expires after a certain time and/or if the link has already been used.

### PR DESCRIPTION
**Pull request by waymao**
Working user reset password.

Awaiting design.

Resolves #15.

### CODE REVIEW

**Comment by waymao** [comment]
TODO: check if the user has signed up (optional, bc auth0 also checks that)
TODO: update the design when it comes out

**Comment by waymao** [comment]
Design question: is it necessary on the backend side to validate the email before sending email?
(valid cases can be: used to have an account, but not with mtw anymore).

**Review by jchin01 — CHANGES_REQUESTED** [review]
I think you might've just overwritten your stuff when you merged from staging.

**Comment by jchin01** [comment]
Branch and issue closed with Auth0 things

**Pull request closed without merging**
